// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACc6vtIFvIllBZDmInwk6hpSt4acCvCzY',
    appId: '1:230542805431:web:8036e75acf50943a22c032',
    messagingSenderId: '230542805431',
    projectId: 'bin-authentication',
    authDomain: 'bin-authentication.firebaseapp.com',
    storageBucket: 'bin-authentication.firebasestorage.app',
    measurementId: 'G-WL60VV0SHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFdkglS6xnbnKz28Rcwpm92uke55wH4u0',
    appId: '1:230542805431:android:09802518a1dc653122c032',
    messagingSenderId: '230542805431',
    projectId: 'bin-authentication',
    storageBucket: 'bin-authentication.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUvsTM8j7HrpBDxlvA8ZcoQs3Fh-xNMTU',
    appId: '1:230542805431:ios:b6a2a78d7268b90522c032',
    messagingSenderId: '230542805431',
    projectId: 'bin-authentication',
    storageBucket: 'bin-authentication.firebasestorage.app',
    iosBundleId: 'com.elvin.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUvsTM8j7HrpBDxlvA8ZcoQs3Fh-xNMTU',
    appId: '1:230542805431:ios:5907956856eab66422c032',
    messagingSenderId: '230542805431',
    projectId: 'bin-authentication',
    storageBucket: 'bin-authentication.firebasestorage.app',
    iosBundleId: 'com.example.bin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACc6vtIFvIllBZDmInwk6hpSt4acCvCzY',
    appId: '1:230542805431:web:2c2329c75af0c65122c032',
    messagingSenderId: '230542805431',
    projectId: 'bin-authentication',
    authDomain: 'bin-authentication.firebaseapp.com',
    storageBucket: 'bin-authentication.firebasestorage.app',
    measurementId: 'G-ZW5ZMF4J68',
  );
}
